version: '3.5'
services:
  postgres:
    env_file:
      - config.env
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /pri-system/db/data:/var/lib/postgresql/data
      - /pri-system/db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 20
    networks:
      - pri-network
  core:
    build: .
    env_file:
      - config.env
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker-prod
      JWT_TOKEN: ${JWT_TOKEN}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - pri-network
networks:
  pri-network:
    name: pri-network
    external: true
