name: Docker Image CI

on:
  push:
    branches: [ "SYSPRI-999-Open-source-dev" ]
  pull_request:
    branches: [ "SYSPRI-999-Open-source-dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag core:$(date +%s)
