name: Docker Image CI

on:
  push:
    branches: [ "SYSPRI-999-Open-source-dev" ]
  pull_request:
    branches: [ "SYSPRI-999-Open-source-dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@v3
      - name: 'Build and publish the Docker image'
        run: |
          docker build . --tag ghcr.io/system-pri/pri-core:latest
          docker push ghcr.io/system-pri/pri-core:latest